name: Publish Pipeline
on:
  push:
    tags:
      - 'v*'

jobs:
  docker-publish:
    name: Build & Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Logging in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Publish to Registry
        run: |
          docker buildx build --push \
            --tag jamesgawn/gohelloworld:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .