name: Publish Pipeline
on:
  push:
    tags:
      - 'v*'

jobs:
  docker-publish:
    name: Build & Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - name: Logging in to Docker
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com/ -u jamesgawn --password-stdin
      - name: Publish to Registry
        run: |
          docker buildx build --push \
            --tag docker.pkg.github.com/jamesgawn/gohelloworld/gohelloworld:latest \
            --tag docker.pkg.github.com/jamesgawn/gohelloworld/gohelloworld:${{ steps.get_version.outputs.TAG }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .