name: Publish Pipeline
on:
  push:
    tags:
      - '*.*.*'

jobs:
  docker-publish:
    name: Build & Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            jamesgawn/gohelloworld:latest
            jamesgawn/gohelloworld:${{ GITHUB_REF##*/ }}